

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int PRUcode[] =  {
     0x91042480,
     0x1d04e0e0,
     0x81042480,
     0x24deadc7,
     0x24beef87,
     0x81003887,
     0x2400231f,
     0x247fffc0,
     0x24ffff80,
     0xd110ff00,
     0xc910ff00,
     0x0501e0e0,
     0x5100e006,
     0x81003880,
     0x7f0000fb,
     0x81003880,
     0x240000e1,
     0x7f0000f8,
     0x81003880,
     0x2400231f,
     0x7f0000f3,
     0x2a000000 };

